import numpy as np
import random
import matplotlib.pyplot as plt
import string
y = []

for i in range(100):
    name = random.choice([
    "the godfather",
    "the shawshank redemption",
    "pulp fiction",
    "the dark knight",
    "12 angry men",
    "schindlers list",
    "inception",
    "fight club",
    "forrest gump",
    "the matrix",
    "goodfellas",
    "star wars",
    "the silence of the lambs",
    "jurassic park",
    "saving private ryan",
    "city of god",
    "interstellar",
    "parasite",
    "the green mile",
    "terminator 2 judgment day",
    "back to the future",
    "spirited away",
    "the pianist",
    "psycho",
    "gladiator",
    "the lion king",
    "the departed",
    "whiplash",
    "the prestige",
    "memento",
    "apocalypse now",
    "alien",
    "aliens",
    "coco",
    "django unchained",
    "wall e",
    "the shining",
    "joker",
    "avengers infinity war",
    "spider man into the spider verse",
    "dr strangelove",
    "toy story",
    "amadeus",
    "braveheart",
    "inglourious basterds",
    "good will hunting",
    "2001 a space odyssey",
    "reservoir dogs",
    "vertigo",
    "citizen kane",
    "requiem for a dream",
    "eternal sunshine of the spotless mind",
    "taxi driver",
    "lawrence of arabia",
    "double indemnity",
    "amelie",
    "a clockwork orange",
    "full metal jacket",
    "to kill a mockingbird",
    "scarface",
    "heat",
    "up",
    "the sting",
    "a separation",
    "metropolis",
    "die hard",
    "incendies",
    "snatch",
    "1917",
    "hamilton",
    "downfall",
    "indiana jones and the last crusade",
    "batman begins",
    "l a confidential",
    "green book",
    "toy story 3",
    "unforgiven",
    "logan",
    "rashomon",
    "oldboy",
    "the great dictator",
    "all about eve",
    "the wolf of wall street",
    "room",
    "inside out",
    "blade runner",
    "warrior",
    "v for vendetta",
    "the elephant man",
    "the sixth sense",
    "trainspotting",
    "the truman show",
    "finding nemo",
    "kill bill vol 1",
    "gone girl",
    "grand budapest hotel",
    "hacksaw ridge",
    "the deer hunter",
    "gran torino",
    "fargo",
    "prisoners",
    "mad max fury road",
    "catch me if you can",
    "million dollar baby",
    "harry potter and the deathly hallows",
    "ben hur",
    "the big lebowski",
    "12 years a slave",
    "rocky",
    "platoon",
    "stand by me",
    "network",
    "into the wild",
    "rush",
    "spotlight",
    "hotel rwanda",
    "ratatouille",
    "before sunrise",
    "groundhog day",
    "monsters inc",
    "guardians of the galaxy",
    "deadpool",
    "iron man",
    "thor ragnarok",
    "black panther",
    "wonder woman",
    "man of steel",
    "casino royale",
    "skyfall",
    "goldfinger",
    "dr no",
    "top gun",
    "mission impossible",
    "minority report",
    "edge of tomorrow",
    "district 9",
    "ex machina",
    "arrival",
    "her",
    "get out",
    "us",
    "a quiet place",
    "hereditary",
    "midsommar",
    "the witch",
    "it",
    "halloween",
    "scream",
    "the thing",
    "predator",
    "robocop",
    "total recall",
    "starship troopers",
    "fifth element",
    "avatar",
    "titanic",
    "la la land",
    "moonlight",
    "roma",
    "birdman",
    "boyhood",
    "social network",
    "zodiac",
    "se7en",
    "cast away",
    "apollo 13",
    "gravity",
    "the martian",
    "life of pi",
    "slumdog millionaire",
    "no country for old men",
    "there will be blood",
    "phantom thread",
    "boogie nights",
    "magnolia",
    "dunkirk",
    "tenet",
    "oppenheimer",
    "barbie"
])
    iterations = 0
    print(name)
    while len(name) > 0:
        char_list = list(set(name))
        char = np.random.choice(char_list)
        name = name.replace(char, "")
        iterations += 1
        
    y.append(iterations)
    print(f"Iterations to empty name: {iterations}")
x = range(1, 101)

plt.plot(x, y)
plt.title("Iterations to Empty Movie Names")
plt.xlabel("Iterations")
plt.ylabel("Characters in selected movie name")
plt.grid(True)
plt.show()
